Running SLURM prolog script on pink57
===============================================================================
Job started on Sat Aug  4 18:50:18 BST 2018
Job ID          : 123687
Job name        : saliency-batch
WorkDir         : /mainfs/lyceum/grm1g17/lasagne4bio/test_saliency
Partition       : lyceum
Num hosts       : 1
Num cores       : 14
Num of tasks    : 14
Hosts allocated : pink57
Job Output Follows ...
===============================================================================
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using cuDNN version 7005 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:03:00.0)
/lyceum/grm1g17/.conda/envs/localenv/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using Theano backend.
Traceback (most recent call last):
  File "saliency.py", line 14, in <module>
    from utils import decode, ssConvertMap, ssConvertString, convertPredictQ8Result2HumanReadable, window
  File "/mainfs/lyceum/grm1g17/lasagne4bio/test_saliency/utils.py", line 11, in <module>
    pssmMap_jurtz = {amino: i for i, amino in enumerate(pssm)}
NameError: name 'pssm' is not defined
